### ISSUE TITLE
STORE BUG

### ISSUE THREAD

**Issue by Temouchenty** [PickleModifications/pickle_prisons#4]
CANTEEN STORE AND PRISON PLUG STORE NOT OPENING

**Comment by mrdigital0** [comment]
Check our items are correct

**Comment by Temouchenty** [comment]
i have same items in shared nd config
![image](https://github.com/PickleModifications/pickle_prisons/assets/71113131/13c8bbe0-a630-4138-bb57-06eb9d75b684)

**Comment by mrdigital0** [comment]
show client.lua line 67

**Comment by mrdigital0** [comment]
i had this same issue and i had to rename bread to sandwich in the config file and water to water_bottle

**Comment by Temouchenty** [comment]
right now store working just fine but prison plug not working

![image](https://github.com/PickleModifications/pickle_prisons/assets/71113131/1f875a46-7804-41ba-87a6-78210a54e5e9)

**Comment by Temouchenty** [comment]
its working now thnk u i just changed weapon name from the config file
